AllCops:
  Exclude:
  - 'bin/**/*'
  - 'db/**/*'
  - 'log/**/*'
  - 'config/**/*'

Style/Documentation:
  Enabled: false

Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"

Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"